language: python
python:
  - '2.7'
virtualenv:
  system_site_packages: true
notifications:
  slack:
    secure: iqdNG6wdkp86zQ2dSY3OMW3VwvPlBwtcbeaZmcy12XXqxxYgfATHEK9sEW20zxU4iZCSoprycN8qFjtna7yjnCUkx6Vd1kGw9N8PvEfpuwwGhORcF1VE5YKC34fP+F7AUuNXMkPNe/R2RAtN2qtM6q1dnuYTQZIR8G+xd37qOP8=
before_install:
  - sudo apt-get update -qq
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b"
  - export PATH=/home/travis/miniconda/bin:$PATH
  - export PATH=/home/travis/miniconda/lib/python2.7/site-packages:$PATH
  - export PATH=/home/travis/virtualenv/python2.7_with_system_site_packages/bin/python2.7:$PATH
  - conda update --yes conda
  - pip install six>=1.3
  - sudo apt-get install libcurl4-openssl-dev python-dev
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
  - sudo pip install homura
  - sudo pip install termcolor
  - sudo apt-get install python-dateutil
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib gdal scikit-image requests six nose dateutil
  - conda config --add channels https://conda.binstar.org/rsignell
  - conda install --yes -c https://conda.binstar.org/ioos-rhel6 rasterio
  - pip install --install-option="--no-cython-compile" cython
  - export PATH=$PATH:$PWD/landsat-util/landsat/
  - pwd
  - ls -la
  - cd landsat-util
  - pip install -e .
  - cd ..
  - pip install -r requirements.txt
script:
  - py.test -s -v test_render_1.py
